url: https://blog.apekind.dev

tag_page_layout: tag_page
tag_page_dir: tag

collections_dir: collections
permalink: /:collection/:title

formats:
  - .svg
  - .png
  - .jpg
  - .webp
  - .gif

collections:
  serial:
    output: true
    permalink: /:collection/:name