### GENERAL SETTINGS ###

# Site settings
title: ANDERSON ANTUNES
analytics: UA-57119340-1
baseurl: "" #important: start with /
url: "http://anderson-blog.github.io"

# Build settings
markdown: kramdown
permalink: /:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#22405C" 
  primary_rgb: "247,0,49" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#141414"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

links :
  Home : /
  Blog : /blog
  Portfolio : /portfolio
  About: /about

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc), see http://fortawesome.github.io/Font-Awesome/icons/#brand . Shown in footer.
social:
  - title: youtube-play
    url: https://www.youtube.com/channel/UCMhDYv6UYFNm_qKz87yIKyg
  - title: facebook-square
    url: https://www.facebook.com/anderson.utf
  - title: instagram
    url: http://instagram.com/anderson_antunes_
  - title: github
    url: https://github.com/anderson-

logos:
  - name: java
    img: 1.png
  - name: linux
    img: 2.png
  - name: arduino
    img: 3.png
  - name: git
    img: 4.png
  - name: open hardware
    img: 5.png
  - name: gnome
    img: 6.png
    
defaults:
  -
    scope:
      path: _posts/en
    values:
      lang: en
  -
    scope:
      path: _posts/pt
    values:
      lang: pt

t:
  en:
    home:
      name: "HOME"
      url: "/"
    blog:
      name: "BLOG"
      url: "/blog/"
    portfolio:	
      name: "PORTFOLIO"
      url: "/portfolio/"
    about:
      name: "ABOUT"
      url: "/about/"
  pt:
    home:
      name: "HOME"
      url: "/br/"
    blog:
      name: "BLOG"
      url: "/blog_br/"
    portfolio:	
      name: "PORTFOLIO"
      url: "/portfolio_br/"
    about:
      name: "SOBRE MIM"
      url: "/about_br/"

label:
  en:
    subscribe: "Subscribe"
    quicknotes: "Quick Notes"
    recentposts: "Recent Posts"
    categories: "Categories"
    readmore: "Read More"
    pages: "Pages"
    sociallinks: "Social Links"
    timeline: "My Timeline"
    comment: "Comment"
    comments: "Comments"
  pt:
    subscribe: "Inscreva-se"
    quicknotes: "Minhas Notas"
    recentposts: "Últimos Posts"
    categories: "Categorias"
    readmore: "Leia Mais"
    pages: "Páginas"
    sociallinks: "Redes Sociais"
    timeline: "Minha Linha do Tempo"
    comment: "Comentário"
    comments: "Comentários"